kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-backup-data
  annotations:
    volume.beta.kubernetes.io/storage-class: hostpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
